import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shishir 2025",
  description: "Generated by create next app",
};


import { SessionProvider } from "next-auth/react";


//Components
import { ClientProviders } from "@/app/components/ClientProviders";



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <NavBar />
        <ClientProviders>
          {children}
        </ClientProviders>
        <Footer />
      </body>
    </html>
  );
}
